[View in Colaboratory](https://colab.research.google.com/github/megadarkparticle/Test/blob/master/PyTorch_Lab_1_Getting_Started.ipynb)

# PyTorch Lab 1

Written by Prachya Boonkwan (Arm)

In [0]:
!pip install -q http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl torchvision

## Getting Started

Let's give it a try on PyTorch. We are going to do simple vector/matrix computation.

## Header

This part is the header of the code. My favorite import aliases for PyTorch are as follows. This will be very useful for speed coding.

In [0]:
#!/usr/bin/env python3
#-*- coding: utf-8 -*-

import torch as T
import torch.nn as N
import torch.optim as O

*TRICK:* You can partially type in a command and press `[TAB]` to complete it. In the following line, remove the comment sign `#`, then type in `T.FloatT` after the equal sign. Press `[TAB]` to see a dropdown list of available commands.

In [0]:
# my_matrix = 

------

## Vectors

**0-Vector:** This is how we declare a vector. Let's begin with a 0-vector using the command `T.zeros`. For example, `T.zeros(3)` will create the vector $\left[ 
\begin{array}{ccc}
    0 & 0 & 0
\end{array} \right]$.

In [0]:
vec1 = T.zeros(3)     # Change the number of elements for more fun.
print(vec1)

tensor([0., 0., 0.])


**1-Vector:** This is how we declare a 1-vector with the command `T.ones`. For example, `T.ones(3)` will create the vector $\left[ 
\begin{array}{ccc}
    1 & 1 & 1
\end{array} \right]$.

In [0]:
vec2 = T.ones(3)      # Change the number of elements for more fun.
print(vec2)

tensor([1., 1., 1.])


**Custom Vector:** We declare a custom vector with `T.FloatTensor`. Here is how we define the vector $
\left[ \begin{array}{ccc}
    1, 2, 3
\end{array} \right]
$.

In [0]:
vec3 = T.FloatTensor([1.0, 2.0, 3.0])    # Add more elements for more fun.
print(vec3)

tensor([1., 2., 3.])


**Size:** We can find the size of a vector with the method `size()`.

In [0]:
print(vec3.size())

torch.Size([3])


**Randomized Vector:** Randomized vectors can be defined with `T.randn`.

In [0]:
vec4 = T.randn(3)
print(vec4)

tensor([1.6993, 0.2972, 0.9210])


**Indexing:** We can refer to an element in a vector by indexing `[]`. Note that the index starts with 0.

In [0]:
print(vec3[1])           # the second element

tensor(2.)


In [0]:
print(vec3[2])           # the third element

tensor(3.)


In [0]:
# print(vec3[20])          # This will cause an error message due to out-of-bounds indexing

IndexError: ignored

**Element Setting:** We can also set the value of a vector's element by indexing `[]`. For example, let's set the second element of `vec3` to be 100.

In [0]:
vec5 = T.FloatTensor([1.0, 2.0, 3.0])

print('Before: vec5 = {}'.format(vec5))
vec5[1] = 100            # Set the second element to be 100.
print('After : vec5 = {}'.format(vec5))

Before: vec5 = tensor([1., 2., 3.])
After : vec5 = tensor([  1., 100.,   3.])


-----

## Matrices

**0-Vector:** This is how we declare a matrix. A 0-matrix can again be defined with `T.zeros`, but this time we identify the size of each dimension, too. For example, `T.zeros(3, 4)` will create the matrix

$$\left[ 
\begin{array}{cccc}
    0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0
\end{array} \right]_{3 \times 4}
$$

In [0]:
mat1 = T.zeros(3, 4)     # Change the number of elements on any dimension.
print(mat1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


**1-Vector:** We define a 1-matrix with `T.ones` in the same fashion. For example, `T.ones(3, 4)` will create the matrix

$$\left[ 
\begin{array}{cccc}
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1
\end{array} \right]_{3 \times 4}
$$

In [0]:
mat2 = T.ones(3, 4)      # Change the number of elements on any dimension.
print(mat2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**Identity Matrix:** This is how you define an identity matrix with `T.eye`. For example, `T.eye(3)` will create the 3-dimensional identity matrix

$$\left[ 
\begin{array}{ccc}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{array} \right]_{3 \times 3}
$$

In [0]:
mat3 = T.eye(3, 4)       # Change the number of elements on any dimension.
print(mat3)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


**Randomized Matrix:** We define a randomized matrix with `T.randn`.

In [0]:
mat_rand = T.randn(3, 4)        # Change the number of elements on any dimension.
print(mat_rand)

tensor([[-0.2418, -1.0089, -0.4328,  0.9259],
        [ 0.6646, -0.2759, -0.0984,  0.2388],
        [ 0.9552,  0.1929, -0.1551, -0.5510]])


**Custom Matrix:** A custom matrix can be defined with `T.FloatTensor`. Notice that a 2-dimensional matrix is just a list of lists. Here we define the matrix

$$
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3}
$$

Each row becomes a list. For example, the first row becomes `[1, 2, 3]`, and the second row, `[4, 5, 6]`.

In [0]:
# Play with the elements, rows, or columns for more fun.
mat4 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )
print(mat4)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


**Size:** We can also find the size of a matrix with the method `size()`.

In [0]:
print(mat4.size())

torch.Size([2, 3])


**Cell Indexing and Setting:** We can refer to a particular cell of a matrix by indexing `[]`.

In [0]:
print(mat4[0,1])            # cell (1,2)

tensor(2.)


In [0]:
print(mat4[1,2])            # cell (2,3)

tensor(6.)


In [0]:
mat4 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )

print('Before: mat4 =\n{}'.format(mat4))
mat4[1,2] = 100             # Set the value of cell (2,3) to be 100.
print('After : mat4 =\n{}'.format(mat4))

Before: mat4 =
tensor([[1., 2., 3.],
        [4., 5., 6.]])
After : mat4 =
tensor([[  1.,   2.,   3.],
        [  4.,   5., 100.]])


**Row Indexing:** We can index a row of a matrix by `[]`, too.

In [0]:
mat5 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )

print('row 1 of mat5 = {}'.format(mat5[0]))
print('row 2 of mat5 = {}'.format(mat5[1]))

row 1 of mat5 = tensor([1., 2., 3.])
row 2 of mat5 = tensor([4., 5., 6.])


**Row Setting:** Setting a row is as simple. For example, we can replace the first row of `mat5` by setting `mat5[0]` to be another vector.

In [0]:
mat5 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )

print('Before: mat5 =\n{}'.format(mat5))
mat5[0] = T.FloatTensor([7, 8, 9])
print('After : mat5 =\n{}'.format(mat5))

Before: mat5 =
tensor([[1., 2., 3.],
        [4., 5., 6.]])
After : mat5 =
tensor([[7., 8., 9.],
        [4., 5., 6.]])


**Column Indexing:** We can also get access to a column of a matrix by replacing the row index with `:`.

In [0]:
mat6 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )

print('column 1 of mat6 = {}'.format(mat6[:, 0]))
print('column 2 of mat6 = {}'.format(mat6[:, 1]))
print('column 3 of mat6 = {}'.format(mat6[:, 2]))

column 1 of mat6 = tensor([1., 4.])
column 2 of mat6 = tensor([2., 5.])
column 3 of mat6 = tensor([3., 6.])


**Column Setting:** Setting a column can be as simple. For example, we can replace the first column of `mat6` by setting `mat6[:, 0]` to be another vector.

In [0]:
mat6 = T.FloatTensor( [ [1, 2, 3],
                        [4, 5, 6] ] )

print('Before: mat6 =\n{}'.format(mat6))
mat6[:, 0] = T.FloatTensor([7, 8])
print('After : mat6 =\n{}'.format(mat6))

Before: mat6 =
tensor([[1., 2., 3.],
        [4., 5., 6.]])
After : mat6 =
tensor([[7., 2., 3.],
        [8., 5., 6.]])


-----

## Matrix Computation

In PyTorch, vectors and matrices are treated similarly. Therefore, we can apply mathematical operations such as addition and multiplication on vectors and matrices, given that they have identical sizes.

Let me define two matrices for our short demonstration.

In [0]:
m1 = T.FloatTensor( [ [1, 2, 3],
                      [4, 5, 6] ] )
m2 = T.FloatTensor( [ [ 7,  8,  9],
                      [10, 11, 12] ] )
print('m1 =\n{}'.format(m1))
print('m2 =\n{}'.format(m2))

m1 =
tensor([[1., 2., 3.],
        [4., 5., 6.]])
m2 =
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


**Addition and Subtraction:** We use `+` and `-`, respectively.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] + \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right] & = & \left[ \begin{array}{ccc}
    8 & 10 & 12 \\
    14 & 16 & 18
\end{array} \right]
\end{eqnarray}
$$

In [0]:
m_add = m1 + m2
print('m1 + m2\n{}'.format(m_add))

m1 + m2
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])


$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right] - \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] & = & \left[ \begin{array}{ccc}
    6 & 6 & 6 \\
    6 & 6 & 6
\end{array} \right]
\end{eqnarray}
$$

In [0]:
m_sub = m2 - m1
print('m2 - m1\n{}'.format(m_sub))

m2 - m1
tensor([[6., 6., 6.],
        [6., 6., 6.]])


**Transpose**: We use the method `t()` to transpose a matrix.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]^\top & = & \left[ \begin{array}{cc}
    1 & 4 \\
    2 & 5 \\
    3 & 6
\end{array} \right]
\end{eqnarray}
$$

In [0]:
m_trans = m1.t()
print('transpose(m1)\n{}'.format(m_trans))

transpose(m1)
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


**Scalar Multiplication:** We simply use the operator `*`.

$$
\begin{eqnarray}
4 \times \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] & = & \left[ \begin{array}{ccc}
    4 & 8 & 12 \\
    16 & 20 & 24
\end{array} \right]
\end{eqnarray}
$$

In [0]:
m_smult = 4 * m1
print('4 × m1\n{}'.format(m_smult))

4 × m1
tensor([[ 4.,  8., 12.],
        [16., 20., 24.]])


**Matrix Multiplication:** We use the method `matmul` of the first operand. Do *NOT* use the operator `*` as it is for element-wise multiplication.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \times \left[ \begin{array}{cc}
    7 & 10 \\
    8 & 11 \\
    9 & 12
\end{array} \right]_{3 \times 2} & = & \left[ \begin{array}{cc}
    50 & 68 \\
    122 & 167
\end{array} \right]_{2 \times 2}
\end{eqnarray}
$$

In [0]:
m_mult = m1.matmul(m2.t())
print('m1 × transpose(m2)\n{}'.format(m_mult))

m1 × transpose(m2)
tensor([[ 50.,  68.],
        [122., 167.]])


Notice that multiplication of `m1` and `m2` would not work due to dimension mismatch.

$$
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \times \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right]_{2 \times 3}
$$

In [0]:
# print(m1.matmul(m2))       # This will cause an error message.

**Element-wise Multiplication:** We use the operator `*` for element-wise multiplication.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \otimes \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right]_{2 \times 3} & = & \left[ \begin{array}{ccc}
    7 & 16 & 27 \\
    40 & 55 & 72
\end{array} \right]_{2 \times 3}
\end{eqnarray}
$$

In [0]:
m_emult = m1 * m2
print('m1 * m2\n{}'.format(m_emult))

m1 * m2
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


-----

## Exercises

1. Define the following matrices and compute $\mathbf{A} + \mathbf{B} + 4 \mathbf{C}$, where

$$
\begin{eqnarray}
    \mathbf{A} & = & \left[ \begin{array}{ccc}
        0 & 0 & 0 \\
        0 & 0 & 0
    \end{array} \right] \\
    \mathbf{B} & = & \left[ \begin{array}{ccc}
        1 & 1 & 1 \\
        1 & 1 & 1
    \end{array} \right] \\
    \mathbf{C} & = & \left[ \begin{array}{ccc}
        1 & 0 & 0 \\
        0 & 1 & 0
    \end{array} \right] \\
\end{eqnarray}
$$

In [0]:
mat_a = T.zeros( 2 , 3 )        # Fill in these blanks
mat_b = T.ones( 2 , 3 )         # Fill in these blanks
mat_c = T.eye( 2 , 3 )          # Fill in these blanks
result = mat_a + mat_b + 4 * mat_c       # Fill in this blank
print(result)

tensor([[5., 1., 1.],
        [1., 5., 1.]])


2. Compute $\mathbf{A}^\top \times \mathbf{A}$, where $\mathbf{A}$ is a randomized vector of dimensions $(3, 4)$.

In [0]:
mat_a = T.randn( 3 , 4 )        # Fill in these blanks
result = mat_a.t().matmul(mat_a)     # Fill in this blank
print(result)

tensor([[ 1.6939, -0.5712, -0.9078,  1.1767],
        [-0.5712,  2.1705, -0.3636, -0.3985],
        [-0.9078, -0.3636,  0.8973, -1.1082],
        [ 1.1767, -0.3985, -1.1082,  2.0597]])


3. Compute $ \left( \mathbf{A} \otimes \mathbf{B} \right)^\top \times \mathbf{C}^\top $, where $\mathbf{A}$, $\mathbf{B}$, and $\mathbf{C}$ are randomized matrices of sizes (2, 3), (2, 3), and (3, 2), respectively.

In [0]:
mat_a = T.randn( 2 , 3 )        # Fill in these blanks
mat_b = T.randn( 2 , 3 )        # Fill in these blanks
mat_c = T.randn( 3 , 2 )        # Fill in these blanks
result = (mat_a * mat_b).t().matmul(mat_c.t())      # Fill in this blank
print(result)

tensor([[ 0.4384,  1.3120, -2.1706],
        [ 0.7863,  1.4712, -1.0616],
        [ 0.0168, -0.0603,  0.2720]])


4. Compute $ \mathbf{R} = \mathbf{A}^\top \times \mathbf{A} $, where $\mathbf{A}$ is a randomized matrix of sizes (3, 4). Then replace the first column with

In [0]:
mat_a = T.randn(3, 4)
mat_r = mat_a.t().matmul(mat_a)
print(mat_r)

tensor([[ 3.8523,  1.3193, -3.4558, -1.4172],
        [ 1.3193,  2.0479, -0.4592, -0.5778],
        [-3.4558, -0.4592,  3.4425,  1.3251],
        [-1.4172, -0.5778,  1.3251,  1.1983]])
